version: '3.7'

services:
  mongo_db:
    image: mongo:4.2.12
    command: ["mongod", "--replSet", "test-rs"]
    networks:
      - mongo-net
    ports:
      - 27017:27017
    volumes:
      - mongoData:/data/db
      - mongoConfig:/data/configdb
    deploy:
      mode: global
      resources:
        limits:
          memory: 1G
          cpus: '1.5'
        reservations:
          memory: 512M
          cpus: '0.5'
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - node.platform.arch == arm
          - node.platform.os == linux
          - node.labels.mongo == replica

  mongo_express:
    image: mongo-express:0.54.0
    networks:
      - mongo-net
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=default
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - "8081:8081"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - node.role == manager
          - node.platform.arch == arm
          - node.platform.os == linux
          - node.labels.mongo == manager
        preferences:
          - spread: node.labels.rack
          - spread: node.labels.datacenter
    depends_on:
      - mongo_db

networks:
  mongo-net:
    external: true

volumes:
  mongoData:
  mongoConfig:
