version: '3.7'

services:
  mongo_db:
    image: mongo:4.2.12
    ports:
      - 27017:27017
    deploy:
      placement:
        constraints:
          - node.role == manager  # Ensure the service runs only on manager node

    volumes:
      - /C/Mine/mongoData:/data/db

  mongo_express:
    image: mongo-express:0.54.0
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=default
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - "8081:8081"
    restart: on-failure
    deploy:
      placement:
        constraints:
          - node.role == manager  # Ensure the service runs only on manager node

    depends_on:
      - mongo_db
