version: '3.7'

services:
  mongo_db:
    image: mongo:4.2.12
    command: ["mongod", "--replSet", "test-rs"]
    networks:
      - mongo-net
    ports:
      - "27017-27027:27017"
    volumes:
      - mongoData:/data/db
      - mongoConfig:/data/configdb
    deploy:
      mode: global  # Deploys one instance on each node
      #mode: replicated
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        preferences:
          - spread: node.labels.datacenter
        constraints:
          #- node.labels.mongo.replica == 1
          - node.labels.datacenter == group1
          - node.labels.datacenter == group2
          - node.labels.rack == worker
          - node.labels.rack == manager

  mongo_express:
    image: mongo-express:0.54.0
    networks:
      - mongo-net
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: "default"
      ME_CONFIG_MONGODB_SERVER: mongo_db
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - "8081:8081"
    volumes:
      - mongoData:/data/db
      - mongoConfig:/data/configdb
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        preferences:
          - spread: node.labels.datacenter
        constraints:
#          - node.labels.mongo.replica == 1
          - node.labels.datacenter == group1
          - node.labels.rack == manager
    depends_on:
      - mongo_db

volumes:
  mongoData:
  mongoConfig:

networks:
  mongo-net:
    external: true
