picocluster64@pc0:~ $ sudo cat docker-compose.yml
version: '3.7'

services:
  mongo_db:
    image: mongo:4.2.12
    command: ["mongod", "--replSet", "test-rs"]
    networks:
      - mongo-net
    ports:
      - "27017:27017"
    volumes:
      - mongoData:/data/db
      - mongoConfig:/data/configdb
    deploy:
      #mode: global
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:

          - node.labels.mongo.replica == 1
          - node.labels.datacenter == group1
          - node.labels.datacenter == group2
        preferences:
          - spread: node.labels.datacenter
  mongo_express:
    image: mongo-express:0.54.0
    networks:
      - mongo-net
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: "default"
      ME_CONFIG_MONGODB_SERVER: mongo_db
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - "8081:8081"
    volumes:
       - mongoData:/data/db
       - mongoConfig:/data/configdb
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - node.labels.mongo.replica == 1
          - node.role == manager  # Only deploy on the manager node
          - node.labels.datacenter == group1
        preferences:
          - spread: node.labels.datacenter
    depends_on:
      - mongo_db

volumes:
  mongoData:
  mongoConfig:

networks:
  mongo-net:
    external: true
picocluster64@pc0:~ $
