version: '3.7'
services:
  arangodb_db_container:
    image: arangodb/arangodb:3.12.0.2
   # environment:
   #   ARANGO_ROOT_PASSWORD: rootpassword
    networks:
      - arango-net
    ports:
      - 8529:8529

    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps
networks:
  arango-net:
    external: true
volumes:
  arangodb_data_container:
  arangodb_apps_data_container:
