version: '3.8'

services:
  voltdb:
    image: voltdb/kvbenchmark:latest
    container_name: voltdb
    ports:
      - "21212:21212"   # VoltDB management port
      - "54321:54321"   # VoltDB client port (customize if necessary)
    environment:
      - VOLTDB_CLUSTER_NAME=myvoltdbcluster
      - VOLTDB_PARTITIONS=4
      - VOLTDB_REPLICAS=1
    volumes:
      - voltdb_data:/voltdb/data
    restart: always

volumes:
  voltdb_data:



